# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v2-${{ hashFiles('package-lock.json') }}
          restore-keys: yarn-v2-
      - run: yarn
        if: steps.cache.outputs.cache-hit != 'true'
      - run: yarn hardhat test
      - run: npx hardhat run scripts/deploy.js --network rinkeby
        env:
          FORCE_COLOR: 1
